#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/MinsharaMask.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/video.jar:$APPDIR/lib/opencv-245.jar:$APPDIR/lib/opencv_processing.jar:$APPDIR/lib/G4P.jar" MinsharaMask "$@"
